from enum import Enum


class MS(str, Enum):
    BADGE = "MS_BADGE"
    BADGE_POST_FIRST = "MS_BADGE_POST_FIRST"
    BADGE_POST_280_CHAR = "MS_BADGE_POST_280_CHAR"
    BADGE_POST_CONSECUTIVE_7 = "MS_BADGE_POST_CONSECUTIVE_7"
    BADGE_POST_EARLY_3 = "MS_BADGE_POST_EARLY_3"
    BADGE_CHEESE_TOTAL_50 = "MS_BADGE_CHEESE_TOTAL_50"
    BADGE_CHRISTMAS = "MS_BADGE_CHRISTMAS"

    DAILY = "MS_DAILY"
    DAILY_LIKE_3_PER_DAY = "MS_DAILY_LIKE_3_PER_DAY"
    DAILY_POST_GENERAL = "MS_DAILY_POST_GENERAL"

    LV_UP = "MS_LV_UP"
