from enum import Enum


class ProductCodeList(str, Enum):
    PD_CL_PURPLE_001 = "PD_CL_PURPLE_001"
    PD_CL_NAVY_001 = "PD_CL_NAVY_001"
    PD_CL_PINK_001 = "PD_CL_PINK_001"
    PD_CL_YELLOW_001 = "PD_CL_YELLOW_001"
    PD_CL_GREEN_001 = "PD_CL_GREEN_001"
    PD_EM_EXCITED = "PD_EM_EXCITED"
    PD_EM_FUN = "PD_EM_FUN"
    PD_EM_RELAXED = "PD_EM_RELAXED"
    PD_EM_APATHETIC = "PD_EM_APATHETIC"
    PD_EM_LONELY = "PD_EM_LONELY"
    PD_EM_COMPLEX = "PD_EM_COMPLEX"
    PD_PLUS_MONTH_1_KR = "PD_PLUS_MONTH_1_KR"
    PD_PLUS_YEAR_1_KR = "PD_PLUS_YEAR_1_KR"

    # 뱃지 구매 테스트용
    PD_BG_CHRISTMAS_2024 = "PD_BG_CHRISTMAS_2024"
    PD_TEST = "PD_TEST"
